### ISSUE TITLE
aws-sso site add --domain --username: ERROR

### ISSUE THREAD

**Issue by sapporo94** [rkhullar/aws-sso#5]
Hi rajan,

I am trying to setup the aws-sso for one of the developer and when i do the command, i am getting the following error:

aws-sso % aws-sso site add --domain sso.XXX.com --username {you_name}
Traceback (most recent call last):
  File "/Users/XXX/Lab/tools/aws-sso/venv/bin/aws-sso", line 8, in <module>
    sys.exit(main())
  File "/Users/XXX/Lab/tools/aws-sso/venv/lib/python3.10/site-packages/aws_sso/command_line.py", line 66, in main
    service: AbstractService = service_def.service_type(common_params, service_params)
  File "/Users/XXX/Lab/tools/aws-sso/venv/lib/python3.10/site-packages/aws_sso/abstract.py", line 14, in __init__
    self.params: NamedTuple = combine_named_tuples(common_params, service_params, handle_methods=True)
  File "/Users/XXX/Lab/tools/aws-sso/venv/lib/python3.10/site-packages/aws_sso/utils/named_tuple.py", line 18, in combine_named_tuples
    field_types = [field_type for named_tuple in named_tuples for field_type in named_tuple._field_types.items()]
  File "/Users/XXX/Lab/tools/aws-sso/venv/lib/python3.10/site-packages/aws_sso/utils/named_tuple.py", line 18, in <listcomp>
    field_types = [field_type for named_tuple in named_tuples for field_type in named_tuple._field_types.items()]
AttributeError: 'CommonParams' object has no attribute '_field_types'

It is the same for everyone, but only getting the error for one person on Mac. And the python version is 3.10.1 and 3.10.4.
As we cannot use 3.7.8 as prescribed.

Please let me know, how to resolve this?

Thanks!

**Comment by rkhullar** [comment]
Hi @sapporo94, I actually don't use this tool anymore for when I need to programmatically sso into aws profiles. I'd suggest moving to the aws cli v2 instead: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html
